In [1]:
# Import libraries 
import pandas as pd 
import numpy as np

In [87]:
installed = pd.read_csv('/Users/tm/LinkNYC/Capstone Data/data/LinkNYC_Locations.csv')
proposed = pd.read_csv('/Users/tm/LinkNYC/Capstone Data/data/LinkNYC_New_Site_Permit_Applications.csv')

In [88]:
installed.columns

Index(['CB Link ID', 'Borough', 'Community Board', 'Council District',
       'Latitude', 'Longitude', 'Project Status', 'Smallest PPT',
       'Street Address', 'Postcode', 'Link Site ID',
       'Link Smoke Tested and Activated (A)', 'Link Installation (A)',
       'Neighborhood Tabulation Area (NTA)',
       'Building Identification Number (BIN)', 'Borough-Block-Lot (BBL)',
       'Census Tract (CT)', 'Cross Street 1', 'Cross Street 2', 'IxN Corner',
       'GF Permit Application ID', 'Location'],
      dtype='object')

In [89]:
proposed.columns

Index(['GF DoITT Submitted to CB (A)', 'Site ID', 'Latitude', 'Longitude',
       'Borough', 'Zoning', 'Council District', 'Community Board',
       'Street Address', 'Cross_Street 1', 'Cross_Street 2', 'Corner_location',
       'Postcode', 'BID', 'Site in Business Improvement District (BID)?',
       'Link In Historic District', 'NTA', 'GF Permit_Appl_Id',
       'DoITT: DoITT NTP Issued (A)', 'GF CB Comment Period Ends (A)',
       'DoITT: GF DoITT Submitted to CB (A)', 'BIN', 'BBL', 'Census Tract',
       'Location 1', 'Legacy ID', 'Site Type', 'Initial Submission (A)',
       'Final Submission (A)'],
      dtype='object')

In [90]:
proposed.head()

,GF DoITT Submitted to CB (A),Site ID,Latitude,Longitude,Borough,Zoning,Council District,Community Board,Street Address,Cross_Street 1,...,GF CB Comment Period Ends (A),DoITT: GF DoITT Submitted to CB (A),BIN,BBL,Census Tract,Location 1,Legacy ID,Site Type,Initial Submission (A),Final Submission (A)
0,08/15/2018,si-01-GF55081,40.64369,-74.07643,Staten Island,C4-2,49,501,36 RICHMOND TERRACE,WALL STREET,...,10/14/2018,08/14/2018,5000073,5000070086,5000300,"(40.6436862, -74.07642539)",LINK-025481,New Site,06/29/2018,NaN
1,08/15/2018,si-01-GF55080,40.64170,-74.07705,Staten Island,C4-2,49,501,26 CENTRAL AVENUE,HYATT STREET,...,10/14/2018,08/14/2018,5000030,5000060021,5000300,"(40.64170058516458, -74.07704509343239)",LINK-025480,New Site,06/28/2018,NaN
2,08/15/2018,si-01-GF55103,40.63866,-74.07589,Staten Island,C4-2,49,501,150 BAY STREET,CENTRAL AVENUE,...,10/14/2018,08/14/2018,5000021,5000010021,5000300,"(40.63865776812222, -74.07589397882975)",LINK-025503,New Site,08/10/2018,NaN
3,01/10/2018,bk-17-GF33566,40.65072,-73.94999,Brooklyn,C1-3,40,317,2846 CHURCH AVENUE,NOSTRAND AVENUE,...,03/11/2018,12/18/2017,3336222,3051050039,3082400,"(40.65072103, -73.94999324)",LINK-024257,New Site,09/25/2017,NaN
4,03/09/2018,BX-02-GF22192,40.82211,-73.89711,Bronx,C2-4,17,202,937 WESTCHESTER AVENUE,INTERVALE AVENUE,...,05/08/2018,12/06/2017,2005390,2026990060,2012901,"(40.82210735, -73.89710558)",LINK-024305,New Site,11/08/2017,NaN

In [91]:
installed.head()

,CB Link ID,Borough,Community Board,Council District,Latitude,Longitude,Project Status,Smallest PPT,Street Address,Postcode,...,Link Installation (A),Neighborhood Tabulation Area (NTA),Building Identification Number (BIN),Borough-Block-Lot (BBL),Census Tract (CT),Cross Street 1,Cross Street 2,IxN Corner,GF Permit Application ID,Location
0,LINK-000498,Manhattan,104,3,40.767358,-73.982564,Live,144139,989 8 AVENUE,10019,...,07/20/2016,Clinton,1026054,1010480033,1013900,WEST 57 STREET,WEST 58 STREET,SW,NaN,"(40.76735759, -73.98256354)"
1,LINK-012278,Manhattan,106,2,40.747055,-73.981061,Live,133555,99 EAST 34 STREET,10016,...,03/03/2018,Murray Hill-Kips Bay,1017084,1008900001,1007200,PARK AVENUE,LEXINGTON AVENUE,NE,NaN,"(40.74705459, -73.98106107)"
2,LINK-013157,Manhattan,110,9,40.801949,-73.949259,Live,138528,99 WEST 116 STREET,10026,...,12/21/2016,Central Harlem South,1085936,1016007501,1019000,LENOX AVENUE,5 AVENUE,NE,NaN,"(40.80194888, -73.9492591)"
3,LINK-018041,Queens,406,29,40.726695,-73.853929,Live,145847,99-40 67 AVENUE,11374,...,05/20/2017,Forest Hills,4075136,4031700027,4071306,QUEENS BOULEVARD,BOOTH STREET,SE,81461.0,"(40.726695, -73.853929)"
4,LINK-000369,Manhattan,108,4,40.761604,-73.966388,Live,121734,991 3 AVENUE,10022,...,02/27/2016,Lenox Hill-Roosevelt Island,1043336,1014140001,1011000,EAST 59 STREET,EAST 60 STREET,NE,NaN,"(40.76160412, -73.9663883)"

In [92]:
installed['status'] = 'installed'
proposed['status'] = 'proposed'

In [93]:
installed = installed[['Latitude','Longitude', 'CB Link ID', 'status', 'Borough']].rename(columns={'CB Link ID':'ID'})

In [94]:
proposed = proposed[['Latitude','Longitude', 'Site ID', 'status', 'Borough']].rename(columns={'Site ID':'ID'})

In [95]:
installed.head()

    Latitude  Longitude           ID     status    Borough
0  40.767358 -73.982564  LINK-000498  installed  Manhattan
1  40.747055 -73.981061  LINK-012278  installed  Manhattan
2  40.801949 -73.949259  LINK-013157  installed  Manhattan
3  40.726695 -73.853929  LINK-018041  installed     Queens
4  40.761604 -73.966388  LINK-000369  installed  Manhattan

In [96]:
proposed.head()

   Latitude  Longitude             ID    status        Borough
0  40.64369  -74.07643  si-01-GF55081  proposed  Staten Island
1  40.64170  -74.07705  si-01-GF55080  proposed  Staten Island
2  40.63866  -74.07589  si-01-GF55103  proposed  Staten Island
3  40.65072  -73.94999  bk-17-GF33566  proposed       Brooklyn
4  40.82211  -73.89711  BX-02-GF22192  proposed          Bronx

In [97]:
data = pd.concat([installed, proposed])

In [98]:
data

      Latitude  Longitude             ID     status        Borough
0    40.767358 -73.982564    LINK-000498  installed      Manhattan
1    40.747055 -73.981061    LINK-012278  installed      Manhattan
2    40.801949 -73.949259    LINK-013157  installed      Manhattan
3    40.726695 -73.853929    LINK-018041  installed         Queens
4    40.761604 -73.966388    LINK-000369  installed      Manhattan
5    40.664166 -73.950920    LINK-010328  installed       Brooklyn
6    40.801001 -73.961448    LINK-013167  installed      Manhattan
7    40.850173 -73.910282    LINK-019315  installed          Bronx
8    40.747114 -73.985245    LINK-008842  installed      Manhattan
9    40.747737 -73.984833    LINK-008843  installed      Manhattan
10   40.734148 -73.988740    LINK-000186  installed      Manhattan
11   40.730258 -74.006629    LINK-010750  installed      Manhattan
12   40.709572 -73.950706    LINK-021138  installed       Brooklyn
13   40.738040 -73.992377    LINK-000214  installed      Manhattan
14   40.762468 -73.974732    LINK-010173  installed      Manhattan
15   40.853930 -73.907502    LINK-011588  installed          Bronx
16   40.736806 -73.993513    LINK-012181  installed      Manhattan
17   40.769839 -73.982502    LINK-000922  installed      Manhattan
18   40.742287 -73.953336    LINK-018209  installed         Queens
19   40.742631 -73.952678    LINK-018207  installed         Queens
20   40.742919 -73.952127    LINK-007136  installed         Queens
21   40.743184 -73.951617    LINK-001290  installed         Queens
22   40.862086 -73.899521    LINK-000087  installed          Bronx
23   40.739409 -73.986712    LINK-013954  installed      Manhattan
24   40.746881 -73.981064    LINK-009082  installed      Manhattan
25   40.807818 -73.945830    LINK-013359  installed      Manhattan
26   40.744847 -73.991677    LINK-014220  installed      Manhattan
27   40.746116 -73.990792    LINK-014075  installed      Manhattan
28   40.787079 -73.971881    LINK-010795  installed      Manhattan
29   40.726495 -73.853138    LINK-018040  installed         Queens
..         ...        ...            ...        ...            ...
275  40.764680 -73.824200  qu-07-GF44266   proposed         Queens
276  40.764380 -73.824900  qu-07-GF44265   proposed         Queens
277  40.764640 -73.822720  qu-07-GF44267   proposed         Queens
278  40.743740 -73.951500  qu-02-GF44307   proposed         Queens
279  40.702130 -73.936990  bk-01-GF33172   proposed       Brooklyn
280  40.765140 -73.818550  qu-07-GF44272   proposed         Queens
281  40.746550 -73.950410  qu-02-GF44309   proposed         Queens
282  40.764790 -73.821460  qu-07-GF44271   proposed         Queens
283  40.745180 -73.950870  qu-02-GF44308   proposed         Queens
284  40.857980 -73.901910  BX-05-GF22074   proposed          Bronx
285  40.858240 -73.902810  BX-05-GF22073   proposed          Bronx
286  40.859290 -73.906750  BX-05-GF22095   proposed          Bronx
287  40.813310 -73.922650  BX-01-GF22094   proposed          Bronx
288  40.811970 -73.925330  BX-01-GF22103   proposed          Bronx
289  40.815140 -73.919540  BX-01-GF22102   proposed          Bronx
290  40.811550 -73.926150  BX-01-GF22122   proposed          Bronx
291  40.813620 -73.922130  BX-01-GF22104   proposed          Bronx
292  40.812730 -73.923840  BX-01-GF22124   proposed          Bronx
293  40.812350 -73.924450  BX-01-GF22123   proposed          Bronx
294  40.814060 -73.921260  BX-01-GF22125   proposed          Bronx
295  40.714710 -73.966520   bk-01-146085   proposed       Brooklyn
296  40.589490 -74.101270   si-02-146098   proposed  Staten Island
297  40.831540 -73.922640   bx-04-145687   proposed          Bronx
298  40.867040 -73.896540   bx-07-145690   proposed          Bronx
299  40.577390 -74.102670   si-02-146099   proposed  Staten Island
300  40.818890 -73.929210   bx-01-145688   proposed          Bronx
301  40.866590 -73.895650   bx-07-145689   proposed          Bronx
302  40.678830 -73.919750   bk-03-GF3096   proposed       Brooklyn
303  40.852970 -73.904800   BX-05-GF2048   proposed          Bronx
304  40.571580 -74.108820   si-02-GF5026   proposed  Staten Island

[2173 rows x 5 columns]

In [99]:
data.groupby('status').count()

           Latitude  Longitude    ID  Borough
status
installed      1868       1868  1868     1868
proposed        305        305   305      305

In [100]:
data['geom'] = list(zip(data.Latitude, data.Longitude))

In [101]:
data.head()

,Latitude,Longitude,ID,status,Borough,geom
0,40.767358,-73.982564,LINK-000498,installed,Manhattan,"(40.767358, -73.982564)"
1,40.747055,-73.981061,LINK-012278,installed,Manhattan,"(40.747054999999996, -73.981061)"
2,40.801949,-73.949259,LINK-013157,installed,Manhattan,"(40.801949, -73.949259)"
3,40.726695,-73.853929,LINK-018041,installed,Queens,"(40.726695, -73.85392900000001)"
4,40.761604,-73.966388,LINK-000369,installed,Manhattan,"(40.761604, -73.966388)"

In [102]:
data.to_csv('links_installed_and_proposed.csv')